### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by rschrenk** [bytebang/moodle-mod_activitymap#1]
[Kurssicherung.zip](https://github.com/bytebang/moodle-mod_activitymap/files/5075191/Kurssicherung.zip)

![fatal_error](https://user-images.githubusercontent.com/8080807/90262112-2652d700-de4e-11ea-98ce-f93538a1bdba.png)

**Comment by bytebang** [comment]
Works on my test moodle 3.8 instance (LAMP stack) without any problems.
- Downloaded the latest version from github
- Installed the plugin
- Added the exported course
- Opened the map

![grafik](https://user-images.githubusercontent.com/11525414/90307073-71fb9400-ded3-11ea-8119-b94433b06186.png)

The same plugin works at my 3.9 test instance (also LAMP stack) and on a Windows machine as well.

Furthermore - the error message indicates an error in the file `<moodle>/web/lib/setuplib.php` - which is not altered by this plugin. 

Can you reproduce this behavior on a fresh moodle instance ?

**Comment by bytebang** [comment]
@rschrenk - any news on this ?

**Comment by rschrenk** [comment]
I tried to analyze the issue some days ago, but I was not able to find a cause for this error.

**Comment by bytebang** [comment]
Strange - since you have installed the previous version of the plugin on the T1 instance as well.
Does the old version (still) work on T1 ?

**Comment by rschrenk** [comment]
no, I had the same error with the previous plugin.

**Comment by rschrenk** [comment]
Great, after re-installing the plugin, everything works now as expected!
