### ISSUE TITLE
Activities hidden by restriction condition still displayed by the module

### ISSUE THREAD

**Issue by mudrd8mz** [bytebang/moodle-mod_activitymap#10]
When the restriction is set up in a way that it is not expected to be displayed to students at all, the module is still displaying its name. It might be better to not display such dependant at all, as that was clearly the course designer intention.

**Comment by bytebang** [comment]
I can confirm: This works for activities which are not linked to other ones. 

As soon as the hidden activity is on the beginning of a "chain" then it is rendered differently. This looks like this:
![image](https://user-images.githubusercontent.com/11525414/106281194-2baaaf00-623f-11eb-8270-12245cf2c771.png)

Here the "Simple Activity" is hidden, but still displayed.
