### ISSUE TITLE
Fails when using "Previous activity with completion" condition

### ISSUE THREAD

**Issue by mudrd8mz** [bytebang/moodle-mod_activitymap#11]
When using Previous activity with condition:

![image](https://user-images.githubusercontent.com/85831/106274706-f1d4ab00-6234-11eb-9eec-3408bd1b715a.png)

there is a PHP notice displayed that breaks the output and the rendering fails:

digraph course_2 { graph [fontname = "helvetica" tooltip="C001" ranksep="0.5" nodesep="0.25" splines="spline" ]; node [fontname = "helvetica"]; edge [fontname = "helvetica"]; rankdir=LR; # All activities cm_6 [ shape="box" label= < Page 001 > tooltip="Page 001" fontcolor="black" URL="http://glux/mdk/m310/mod/page/view.php?id=6" ]; cm_4 [ shape="box" label= < Test - assertions > tooltip="Test - assertions" fontcolor="black" URL="http://glux/mdk/m310/mod/workshop/view.php?id=4" ]; # Things that need to be completed cm_-1 -> cm_4 [ ]; # Dependent nodes which are not part of the current selection

Notice: Undefined offset: -1 in /home/mudrd8mz/www/mdk/m310/moodle/mod/activitymap/gvizdot.php on line 469

Notice: Trying to get property 'name' of non-object in /home/mudrd8mz/www/mdk/m310/moodle/mod/activitymap/gvizdot.php on line 469
cm_-1 [style="dotted" fontcolor="red" label="cm_-1" tooltip="Unknown existing activity" ] # Activites according to sections }

**Comment by bytebang** [comment]
Can you please export the course and upload it here.
So I can try reproduce the error.
