### ISSUE TITLE
Print button

### ISSUE THREAD

**Issue by lassnj** [bytebang/moodle-mod_activitymap#18]
**Is your feature request related to a problem? Please describe.**
Parents and students (10-14 years old) would like to print the activity map.

**Describe the solution you'd like**
There should be a print button available, that prints only the generated activity map and not the whole browser window.

**Describe alternatives you've considered**
Browser print function or Screenshot of the activity map is not very helpful for inexperienced users

**Additional context**

**Comment by bytebang** [comment]
The quick and dirty solution is to add a Link to moodle which shows the map without the moodle context.

This can be done by adding `&plain=1` to the URL where the activitymap is linked within moodle. This renders a png which can be printed from within the browser.

* Create an activitymap (that you want to print)
* Right mouse button on the activity: Copy Link. The link looks something like this: `https://my.moodle.xyz/mod/activitymap/view.php?id=2463403`
* Create a URL Activity (without activity completion) where the external URL points to the plain version of the map: `https://my.moodle.xyz/mod/activitymap/view.php?id=2463403&plain=1`

In my course this looks something like this:

![image](https://user-images.githubusercontent.com/11525414/140982645-a2e7b7bd-f648-4830-99fe-1917d136b934.png)

Please tell me if this works for you or if you really need the print button

**Comment by bytebang** [comment]
Closed issue due to lack of feedback
