### ISSUE TITLE
CSS to set size or font in the graph

### ISSUE THREAD

**Issue by dairaine** [bytebang/moodle-mod_activitymap#21]
**Is your feature request related to a problem? Please describe.**
My request is due to overflow of title in nodes in the graph. It seems the style is embeded in the code.

**Describe the solution you'd like**
A way to set style using css or any other means, 

**Describe alternatives you've considered**
- css class to set style
- an interface for setting few styles properties, particularly font and size

**Additional context**

**Comment by bytebang** [comment]
The style is generated inside https://viz-js.com/ - which is outside of our scope.
We use this library to render the graph and therefore also the nodes.

As far as I can tell, there are no css injections possible. However, if you find a way/solution there, then it should work also for the activitymap plugin.
