### ISSUE TITLE
font color unavailable activities 

### ISSUE THREAD

**Issue by AndreasPoetscher** [bytebang/moodle-mod_activitymap#3]
As a student, the text for unavailable activities has a bad visibility with some background colors. 
![Schrift](https://user-images.githubusercontent.com/45976426/90505557-193a2e80-e153-11ea-9d80-d7228b89486a.PNG)

**Comment by bytebang** [comment]
I see that the "Radnom color" option is choosed. As a quick fix you can alter the Section name "Vertiefung ..." by adding a blank at the beginning or at the end. This will result into another color.
