### ISSUE TITLE
label with map embedded in an iframe error 

### ISSUE THREAD

**Issue by AndreasPoetscher** [bytebang/moodle-mod_activitymap#5]
If the map is included in a label embedded in an iframe, the map doesnt work. See attached course

[backup-moodle2-course-3-4it_testkurs-20200818-1331-nu.zip](https://github.com/bytebang/moodle-mod_activitymap/files/5090074/backup-moodle2-course-3-4it_testkurs-20200818-1331-nu.zip)

**Comment by bytebang** [comment]
First: Actionmap does display everything that has completion enabled. If you create a label with an iframe to the same actionmap (and completion enabled) then this leads to undefined behaviour -> Step 1: Disable completion for the label which should display iframe actionmaps.


Second: It is better to use relative URLs within iframes. After i imported the course i had to tewak the actionmap-id.

This works for me: 
~~~~
<iframe src="../mod/activitymap/view.php?id=399?id=399&amp;plain=1" seamless="" name="CV &amp; CG" width="600" height="1000">
</iframe>
~~~~
