### ISSUE TITLE
Add exclusion of sections

### ISSUE THREAD

**Issue by lassnj** [bytebang/moodle-mod_activitymap#6]
Only three options are available to query the content:
- All sections
- All sections grouped
- Current section

It should be possible to exclude some sections but span the graph over other sections. E.g. I have a forum activity in section one, and a section for tests and exams that I want to exclude, but I want to span the graph over all other sections of the course.

**Comment by bytebang** [comment]
This feature is indeed not implemented. 

If you want to exclude some activities, then just set the _Completion Tracking_ option to the value `Do not indicate activity completion`. This should do the trick.
